### ISSUE TITLE
lang: Japanese translation available

### ISSUE THREAD

**Issue by yuja** [chantra/redmine_whining#1]
Hi, I added Japanese translation of messages.

Available on GitHub: yuja/redmine_whining@ac9f3c1c9dafbd3f8368e16cb7dd6ca05fba9a16

**Comment by chantra** [comment]
Hi Yuja.

Sorry for that real late reply. 
I have merged it within my repository now.
Tks.

**Comment by yuja** [comment]
Thank you for mergin in it.
