### ISSUE TITLE
undefined method render_multipart for WhiningMailer

### ISSUE THREAD

**Issue by earthgecko** [chantra/redmine_whining#10]
Seem to be having a problem that I cannot find any info on.  Apologies ruby is not my forte..

On running the cron we get an error.  The cron is run as daemon same user as the web server.

Running:
ruby --version
ruby 1.8.6 (2010-02-05 patchlevel 399) [x86_64-linux]

gem --version
1.3.6

rake --version
rake, version 0.8.7

And Redmine 0.8.7.stable.3675 (MySQL)

Running the same cron command with --trace reports the following:

<pre><code># cd /opt/redmine-0.8 && /usr/bin/rake --trace redmine:send_whining days=7 RAILS_ENV="production"
(in /opt/redmine-0.8)
** Invoke redmine:send_whining (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:send_whining
rake aborted!
undefined method `render_multipart' for #<WhiningMailer:0x2b2a1b6d6aa8>
/opt/redmine-0.8/vendor/plugins/redmine_whining/lib/tasks/whining.rake:52:in `whining'
/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.1.2/lib/action_mailer/base.rb:446:in `__send__'
/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.1.2/lib/action_mailer/base.rb:446:in `create!'
/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.1.2/lib/action_mailer/base.rb:439:in `initialize'
/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.1.2/lib/action_mailer/base.rb:383:in `new'
/usr/local/lib/ruby/gems/1.8/gems/actionmailer-2.1.2/lib/action_mailer/base.rb:383:in `method_missing'
/opt/redmine-0.8/vendor/plugins/redmine_whining/lib/tasks/whining.rake:68:in `whinings'
/opt/redmine-0.8/vendor/plugins/redmine_whining/lib/tasks/whining.rake:67:in `each'
/opt/redmine-0.8/vendor/plugins/redmine_whining/lib/tasks/whining.rake:67:in `whinings'
/opt/redmine-0.8/vendor/plugins/redmine_whining/lib/tasks/whining.rake:80
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `call'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in `invoke_with_call_chain'
/usr/local/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in `invoke_with_call_chain'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in `invoke_task'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `each'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
/usr/local/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/usr/bin/rake:19:in `load'
/usr/bin/rake:19
</code></pre>

Any ideas? :)

**Comment by chantra** [comment]
Hum

I dont really know.
http://github.com/chantra/redmine_whining/tarball/v0.0.1 was made against redmine 0.8 so you might want to give it a try to see it this one works.

Other than that, render_multipart should be pulled from http://www.redmine.org/projects/redmine/repository/revisions/3675/entry/trunk/app/models/mailer.rb

I dont really know why it would not work.
Let me know if v0.0.1 get you further.

**Comment by earthgecko** [comment]
Bingo!!!  Thanks chandra, that did it. v0.0.1 works.
