### ISSUE TITLE
missing } in config/locales/fr.yml

### ISSUE THREAD

**Issue by vincentxavier** [chantra/redmine_whining#13]

**Comment by vincentxavier** [comment]
diff --git a/config/locales/fr.yml b/config/locales/fr.yml  
index 8fd1484..acd7e79 100644  
--- a/config/locales/fr.yml  
+++ b/config/locales/fr.yml  
@@ -2,7 +2,7 @@ fr:  
 # Traduction francaise/french translation (c) Vincent-Xavier JUMEL -- 2009  
 # Emmanuel Bretelle  
 # Released under GPL2 licence                                                                                                                                                                                                                                                    
-  mail_body_whining: "{{count}} tache(s) qui vous sont assignees et que vous n'avez pas mis a jour ces {{days} derniers jours:"  
-  mail_body_whining: "{{count}} tache(s) qui vous sont assignees et que vous n'avez pas mis a jour ces {{days}} derniers jours:"  
  mail_subject_whining: "{{count}} tache(s) non mise(s) a jour ces derniers {{days}} jours"  
  whining_whine_when: "Pleurnicher apr�s"  
  days: "jours"

**Comment by chantra** [comment]
Hi vincent-xzvier,

Tks for pointing this out.

I have fixed the typo and pushed the change
