### ISSUE TITLE
Cron Command issue

### ISSUE THREAD

**Issue by george1982** [chantra/redmine_whining#16]
Hello all,

I managed to install the plugin, but I can't get the cron command right. I haven't used the cronjobs before so I am a newby. Redmine version is 1.0.2 stable (mysql). 

The command used in the cronjob is www-data cd /home/mysite/rails_apps/redmine/vendor/plugins/redmine_whining && /usr/bin/rake redmine:send_whining days=45

The email I am getting each working day is:/bin/sh: www-data: command not found

I am sure I am doing something wrong in the command. If somebody could point me in the right direction that would be great.

Should you require any further assistance please do not hesitate to contact us.

Regards,
George

**Comment by chantra** [comment]
how do you run the cron? is it a user cron or system cron?
in My case, I have the following in /etc/cron.d/redmine

0 4 \* \* 1,2,3,4,5     www-data cd /var/www.........

**Comment by george1982** [comment]
Hello Chantra,

Thank you for the reply. I run cron directly from my cPanel if that was the question :S

Any suggestions or if you need any extra information, please let me know.

Once again thank you for your help.
George

**Comment by chantra** [comment]
Hi George,

This seems rather a cpanel issue.

Because you run it in cpanel, you cant change owner (you are not root). And you should not specify the time i guess. So.... the command will start at "cd /....."

Then, you have to adapt it with your own settings.

**Comment by george1982** [comment]
Hi Chantra,

Thank you for the reply.

I changed the command and now I get the following error: 

'rake aborted!
Access denied for user 'root'@'localhost' (using password: NO)
/home/site_name/rails_apps/redmine/Rakefile:10
(See full trace by running task with --trace)
(in /home/site_name/rails_apps/redmine)'

Thanks,
george

**Comment by chantra** [comment]
I would guess you are not passing the RAILS_ENV variable correctly so it cant pick up the right config.

I would recommend you ask for some help on the IRC channel of redmine. People will be able to help you out, and most likely some people use cpanel there.

**Comment by chantra** [comment]
I will close this as it is not a plugin issue per se. But a config in cpanel environment.
