### ISSUE TITLE
Causes loading config/environment.rb twice

### ISSUE THREAD

**Issue by yuja** [chantra/redmine_whining#2]
redmine_whining plugin causes double loading of config/environment.rb, at least, when running rake db:migrate.
This means all plugins are initialized twice, and some plugins raise exception with upcoming Redmine 0.9 series.

We can fix it by specifying config/environment.rb by full-path: yuja/redmine_whining@240a060eb7e628047cdbd930ffcaddf633874400

Stack trace follows:

<pre>
## first pass of loading config/environment.rb
$ rake db:migrate --trace
...
rake aborted!  # by changing embedded/init.rb to raise an exception
...
$REDMINE_ROOT/vendor/plugins/embedded/init.rb:5:in `evaluate_init_rb'
...
./config/environment.rb:20
...
$REDMINE_ROOT/vendor/plugins/redmine_whining/lib/tasks/whining.rake:30
...

## second pass of loading config/environment.rb
$ rake db:migrate --trace
...
rake aborted!
Child already added
$REDMINE_ROOT/lib/redmine/menu_manager.rb:77:in `add'
...
$REDMINE_ROOT/vendor/plugins/embedded/init.rb:6:in `evaluate_init_rb'
...
$REDMINE_ROOT/config/environment.rb:20
...
$GEM_HOME/gems/rails-2.3.5/lib/tasks/misc.rake:4
...
</pre>

**Comment by farviewsoft** [comment]
I was also having this problem.  The change suggested here repaired it.  Sort of.

**Comment by chantra** [comment]
Hi Yuja,

Again sorry for that late reply.
Merged in mean repo. Tks

**Comment by yuja** [comment]
Thanks, too.
