### ISSUE TITLE
Missing template whining_mailer/whining.text.erb

### ISSUE THREAD

**Issue by adeptg** [chantra/redmine_whining#22]
Hello!
After update my Redmine from 1.2.2 to 1.3.0 i have this problem:

/usr/bin/rake -s redmine:send_whining days=30 RAILS_ENV="production"
rake aborted!
Missing template whining_mailer/whining.text.erb in view path vendor/plugins/redmine-graphs-plugin/app/views:vendor/plugins/redmine-mylyn-connector/app/views:vendor/plugins/redmine_charts/app/views:vendor/plugins/redmine_code_review/app/views:vendor/plugins/redmine_google_calendar/app/views:vendor/plugins/redmine_niko_cale/app/views:vendor/plugins/redmine_opensearch/app/views:vendor/plugins/redmine_project_filtering/app/views:vendor/plugins/redmine_scrumdashboard/app/views:vendor/plugins/redmine_time_tracker/app/views:vendor/plugins/redmine_user_profiles/app/views:vendor/plugins/redmine_version_burndown_charts/app/views:vendor/plugins/redmine_whining/app/views:vendor/plugins/simple_ci/app/views:app/views

(See full trace by running task with --trace)

**Comment by chantra** [comment]
Hi adeptg,

Tks for reporting this. This should be fix in commit:5f5e9b2aa6ea6394636ae180a26796eac5694ea7 commit:26ee6ab4ffea70f9e20e3ea4f947e19ef9424e51

**Comment by adeptg** [comment]
Thank you!

**Comment by saintxseiya** [comment]
I still get this Missing template whining_mailer/whining.text.erb in view path app/views
