### ISSUE TITLE
Plugin fails with Redmine 1.4

### ISSUE THREAD

**Issue by myersware** [chantra/redmine_whining#25]
Plugin worked fine with Redmine 1.2 but after upgrade to 1.4 fails with this error:
rake aborted!
uninitialized constant WhiningMailer::ARCondition

Tasks: TOP => redmine:send_whining

**Comment by unicast** [comment]
That's because ARCondition sql binder is removed from redmine
http://www.redmine.org/search?q=ARCondition&all_words=&all_words=1&titles_only=&changesets=1&submit=Submit

**Comment by myersware** [comment]
Support for Redmine 1.4 is not needed, since redmine now include the rake task send_reminders.
So this plugin is now redundant.
