### ISSUE TITLE
Emails is broken

### ISSUE THREAD

**Issue by unbelll** [chantra/redmine_whining#3]
I receive such emails:

<html>
<head>

<style>
body {
 font-family: Verdana, sans-serif;
 font-size: 0.8em;
 color:#484848;
}
h1, h2, h3 { font-family: "Trebuchet MS", Verdana, sans-serif; margin: 0px; }
h1 { font-size: 1.2em; }
h2, h3 { font-size: 1.1em; }
a, a:link, a:visited { color: #2A5685;}
a:hover, a:active { color: #c61a1a; }
a.wiki-anchor { display: none; }
hr {
 width: 100%;
 height: 1px;
 background: #ccc;
 border: 0;
}
.footer {
 font-size: 0.8em;
 font-style: italic;
}
</style>

</head>
<body>
9 issue(s) that are assigned to you haven't been updated in the last 7 days::
- ... issue list has been removed by me

http://redmine.domain/issues?assigned_to_id=25&set_filter=1&sort_key=updated_on&sort_order=asc

<hr />

<span class="footer"><p>You have received this notification because you have either subscribed to it, or are involved in it.<br />To change your notification preferences, please click here: <a class="external" href="http://redmine.domain/my/account">http://redmine.domain/my/account</a></p></span>
</body>
</html>

What I can do to receive normal emails?

**Comment by unbelll** [comment]
Sorry, github was parse html in emails. Html email receive as a plain-text

**Comment by unbelll** [comment]
I accidentally closed the issue. Open it please.

**Comment by farviewsoft** [comment]
I also have this problem.

It looks to me like if you have HTML emails set, it chooses the HTML email template but the email doesn't get properly encoded as HTML instead of text.

I'm running Redmine 0.9.3

Anybody have a solution for this yet?

**Comment by chantra** [comment]
Sorry for the late reply.
I guess this is a dup of #4 now, correct?

**Comment by farviewsoft** [comment]
I agree this would seem to be the case.
