### ISSUE TITLE
Email sending in HTML format are improperly encoded

### ISSUE THREAD

**Issue by farviewsoft** [chantra/redmine_whining#4]
I'm running redmine 0.9.3 on OSX Server and it appears that html emails sent by the rake task are formatted as text.

As a result you se the html source of the email instead of the html email.

**Comment by tdavis** [comment]
Yep, seeing this too.

**Comment by farviewsoft** [comment]
I managed to come up with a solution to this that I'm going to put through the paces before submitting it.  The code is a little sloppy at this point.  I'll create a fork and make my changes there so the author can pull updates.

I think the Mailer changed in 0.9 causing this problem.

**Comment by chantra** [comment]
I wonder if something like http://github.com/chantra/redmine_newissuealerts/commit/862fda018ff32ecd824addf3dade542e28c1eaf4 could help.

Mainly this bit: http://github.com/chantra/redmine_newissuealerts/commit/862fda018ff32ecd824addf3dade542e28c1eaf4#diff-4

**Comment by farviewsoft** [comment]
I fixed it in our implementation by adding:
        render_multipart('whining', body)

to the end of the self.whinings method.  This appeared to be how they handled things in Redmine Core.

**Comment by chantra** [comment]
Hi farviewsoft,

I dont have redmine-0.9 here so i cant really try this fix.
Could you do me a favor and try out the last commit i made on http://github.com/chantra/redmine_whining

I am interested in seeing if http://github.com/chantra/redmine_whining/commit/0daa38d2e277fe574cbab1f16cf6146623fbb9ac fixes the issue for 0.9 and 0.8 serie.

tks

**Comment by wakemate** [comment]
chantra,

A single test indicates your fix works as of revision 3669. Thanks!

**Comment by farviewsoft** [comment]
Looks good to me as well.  Thanks!

**Comment by chantra** [comment]
perfect, i think a v0.3 is welcome then :)
