### ISSUE TITLE
French traduction available

### ISSUE THREAD

**Issue by vincentxavier** [chantra/redmine_whining#5]
I've translated the plugin inot French

**Comment by chantra** [comment]
Hi Vinvent,

Tks for that, could you post the git url so I can merge it. If you dont have a git repository available, can you post it within this ticket.

Tks

**Comment by vincentxavier** [comment]
You can upload it from http://github.com/vincentxavier/redmine_whining

**Comment by chantra** [comment]
Tks,

merged into trunk
