### ISSUE TITLE
Set locale for this plugin

### ISSUE THREAD

**Issue by Salmaja** [chantra/redmine_whining#7]
I need to set russian locale to your plugin. I tried to create files by name ru.yml with UTF-8 encoding. But redmine doesn't send body whining. Instead of it it writes error: "﻿translation missing: ru, mail_body_whining:". Have your plugin any special features for change locale and language? An d ho can I add russian locale.

**Comment by chantra** [comment]
Depending on the version of redmine you are running (or RoR), translation are in 2 different location:
http://github.com/chantra/redmine_whining/tree/master/config/locales/
http://github.com/chantra/redmine_whining/tree/master/lang/

Syntax is slightly different. You might want to compare the 2 en.yml .
If you get the translation working, please fork this repo and send me a pull request.

Tks

**Comment by Salmaja** [comment]
Thank you for your comment. But my problem is another. I got an en.yml, change locale to ru or ru-RU, save it as ru.yml and  wrote russian translation. And after it I got this error. That's why I asked about special locale's registartion. And now this file (ru.yml) looks like this in lang

# Russian strings go here

mail_body_whining: "%d задач, назначенных Вам, не редактиировались %d дней"
mail_subject_whining: "%d задач, назначенных Вам, не редактиировались %d дней"
and  in config/locales 
ru-RU:

# Russian strings go here

  mail_body_whining: "{{count}} задач, назначенных Вам, вар  {{days}} :"
  mail_subject_whining: "{{count}} задач, назначенных Вам, вар {{days}} е"

**Comment by chantra** [comment]
Hum, not sure you have to add ru-RU in config/locales
I would have a file called config/locales/ru.yml
with content:
ru:
  mail_body_whining: "{{count}} задач, назначенных Вам, вар {{days}} :" 
  mail_subject_whining: "{{count}} задач, назначенных Вам, вар {{days}} е"

Mind that there is 2 spaces in front of each strings.

Maybe you could get help from redmine IRC room.
If you dont have any irc client, you can use a live one here http://irc2go.com/pjirc/?room=redmine&net=freenode

**Comment by chantra** [comment]
Hi,

Do you have the translation available so I can apply it to main trunk?

**Comment by chantra** [comment]
Salmaja,

Do you by any chance have an updated version of your translation?

The one provided above does not seem correct as mail_subject_whining and mail_body_whining look the same.

**Comment by chantra** [comment]
closing as I did not get any updates
