### ISSUE TITLE
Can't make plugin to work

### ISSUE THREAD

**Issue by nikitosiusis** [chantra/redmine_whining#8]
I'm using redmine 0.9.4 and have this error when trying to open administration panel.

Processing SettingsController#plugin (for 109.173.60.162 at 2010-06-22 20:09:41) [GET]
  Parameters: {"action"=>"plugin", "id"=>"redmine_whining", "controller"=>"settings"}
Rendering template within layouts/admin
Rendering settings/plugin

ActionView::TemplateError (undefined method `collect' for nil:NilClass) on line #3 of vendor/plugins/redmine_whining/app/views/settings/_whining_settings.html:
1: <p>
2:     <%= content_tag(:label, l(:trackers)) %>
3:     <%= select_tag("settings[trackers]", options_from_collection_for_select(Tracker.all, :id, :name, Setting.plugin_redmine_whining[:trackers].collect { |x| Integer(x)}), :multiple => true) %>
4: </p>
5:
6: <fieldset>

```
vendor/plugins/redmine_whining/app/views/settings/_whining_settings.html:3:in `_run_vendor47plugins47redmine_whining47app47views47settings47_whining_settings46html_locals_object_settings_whining_settings'
app/views/settings/plugin.rhtml:6:in `_run_rhtml_app47views47settings47plugin46rhtml'
app/views/settings/plugin.rhtml:4:in `_run_rhtml_app47views47settings47plugin46rhtml'
/usr/lib/ruby/1.8/mongrel/rails.rb:76:in `process'
/usr/lib/ruby/1.8/mongrel/rails.rb:74:in `synchronize'
/usr/lib/ruby/1.8/mongrel/rails.rb:74:in `process'
/usr/lib/ruby/1.8/mongrel.rb:159:in `process_client'
/usr/lib/ruby/1.8/mongrel.rb:158:in `each'
/usr/lib/ruby/1.8/mongrel.rb:158:in `process_client'
/usr/lib/ruby/1.8/mongrel.rb:285:in `run'
/usr/lib/ruby/1.8/mongrel.rb:285:in `initialize'
/usr/lib/ruby/1.8/mongrel.rb:285:in `new'
/usr/lib/ruby/1.8/mongrel.rb:285:in `run'
/usr/lib/ruby/1.8/mongrel.rb:268:in `initialize'
/usr/lib/ruby/1.8/mongrel.rb:268:in `new'
/usr/lib/ruby/1.8/mongrel.rb:268:in `run'
/usr/lib/ruby/1.8/mongrel/configurator.rb:282:in `run'
/usr/lib/ruby/1.8/mongrel/configurator.rb:281:in `each'
/usr/lib/ruby/1.8/mongrel/configurator.rb:281:in `run'
/usr/lib/ruby/1.8/mongrel/command.rb:212:in `run'
```

Rendering /usr/local/redmine/public/500.html (500 Internal Server Error)

Running rake redmine:send_whining days=7 RAILS_ENV="production" doesn't send any mails also.

**Comment by chantra** [comment]
I am afraid you are using a non stable version.

Could you please use a version from http://github.com/chantra/redmine_whining/downloads please.

You might have to wait a bit before the new feature works properly :s

**Comment by nikitosiusis** [comment]
Yes, I was using version from git. Now I don't have a configure button:) But the plugin works nice. Thanks for fast reply.

**Comment by chantra** [comment]
FYI, this is fixed in new commit
